language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t ydog/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ydog/docker-react npm run test